[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib.workspace = true
#legion.workspace = true
legion = "=0.3.1"
serde = { version = "=1.0.115" }
ron = "=0.6.1"